lane :testUpload do
  ftp(
  host: ENV['FTP_HOST'],
  username: ENV['FTP_USER'],
  password: ENV['FTP_PASSWORD'],
  upload: {
    src: ENV['FTP_UPLOAD_SRC'],
    dest:ENV['FTP_UPLOAD_DEST']
  }
  )
end

lane :testUploadPort do
  ftp(
  host: ENV['FTP_HOST'],
  username: ENV['FTP_USER'],
  password: ENV['FTP_PASSWORD'],
  port: ENV['FTP_PORT'].to_i,
  upload: {
    src: ENV['FTP_UPLOAD_SRC'],
    dest:ENV['FTP_UPLOAD_DEST']
  }
  )
end

lane :testDownload do
  ftp(
  host: ENV['FTP_HOST'],
  username: ENV['FTP_USER'],
  password: ENV['FTP_PASSWORD'],
  download: {
    src: ENV['FTP_DOWNLOAD_SRC'],
    dest:ENV['FTP_DOWNLOAD_DEST']
  }
  )
end

lane :testDownloadPort do
  ftp(
  host: ENV['FTP_HOST'],
  username: ENV['FTP_USER'],
  password: ENV['FTP_PASSWORD'],
  port: ENV['FTP_PORT'].to_i,
  download: {
    src: ENV['FTP_DOWNLOAD_SRC'],
    dest:ENV['FTP_DOWNLOAD_DEST']
  }
  )
end
